### PR TITLE
# Testing To-Do list

### PR DESCRIPTION
**Pull request by gscarv13**
#### This pull request contains several tests, created to validate the functions used on the project

### CODE REVIEW

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ⚠️ 🚧
Hi @gscarv13, Good job so far, all your tests are passing and you did a wide variety of them, however for this project to be approved you need to test for all your functions.

Right now most function from your `helpers.js` is missing. kindly test for all the functions. You can add 2-3 test cases for each of the missing functions.

**Review by umararshadbut — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @gscarv13 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [ ] There are two cases that are failing. Please fix them.

**[OPTIONAL]**
- [x] Please add the test instruction in the README file.
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**Umair**

**Comment by gscarv13** [comment]
## Hello @umararshadbut! 

Thank You for your review, could you please be more specific about which tests are failing?
I just cloned this project and all tests pass here.

**Comment by umararshadbut** [comment]
Hello @gscarv13  
I'm Attaching the screenshot
test

**Comment by gscarv13** [comment]
### Thank You @umararshadbut !

I changed `repalceAll()` function to `replace()` for compatibility reasons

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔**

Hello @gscarv13 
Great work making the requested changes👏👏👏

You can merge👍👍👍

Happy coding💻💻💻

**Pull request merged**
