### PR TITLE
Project: To-Do List App

### PR DESCRIPTION
**Pull request by gscarv13**
## This pull request has the following:

- Single-page app build with HTML, CSS, and Javascript.
- The code has a modular structure making use of ES6 modules.
- Tasks and projects were built using Classes.
- The user can create new projects and tasks.
- The user can mark tasks as done or delete them.

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# STATUS: Changes Required :red_circle: 

## Hello @gscarv13, you have done a great job with this project so far. I really like your readme file very detailed

### To improve:


- [x] Should include a rule for the `node_modules` directory on `.gitignore` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/gitignore_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/))
- [x] You should have a dist folder
- [x] User should be able to edit the details of a to-do item ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/ui_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
- [x] Add some validations so that a user should be asked to fill duedate if they forgot to fill them up

### If you have any question with regards to my requested changes please add a comment here with your question and I will reply ASAP

# HAPPY CODING :computer: :desktop_computer:

**Comment by gscarv13** [comment]
## Thank You for your review @GzimAsani!

The following changes have been applied:
- The user can now edit `title`, `description`, `priority` and `date` clicking over the desired element
- The details are hidden by default
- The user will have a visual response when required to fill in the task creation form properly

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️
Hey @gscarv13, Great job I love the UI design. However few changes is required for us to approve your project
### Highlights:

- [x] Should include a rule for the node_modules directory on .gitignore (screenshot from Pathwright) ✔️ 
- [x]  You should have a dist folder ✔️ 
- [x]  Add some validations so that a user should be asked to fill duedate if they forgot to fill them ✔️ 
### To Improve:
 - [x]  User can edit details but the `edit` anchor is not working. kindly make it working to be able to edit the details
 
#  [ OPTIONAL] 
- [ ]  Add some validations for Description

**Review by bellom — APPROVED** [review]
## Hi @gscarv13  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
